/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MusicAnalysis = IDL.Record({
  'tempo' : IDL.Nat,
  'emotion' : IDL.Text,
  'genre' : IDL.Text,
  'rhythm' : IDL.Text,
});
export const VideoRecord = IDL.Record({
  'id' : IDL.Text,
  'user' : IDL.Principal,
  'audioFile' : ExternalBlob,
  'videoFile' : IDL.Opt(ExternalBlob),
  'analysis' : MusicAnalysis,
});
export const UploadResult = IDL.Record({
  'id' : IDL.Text,
  'audioFile' : ExternalBlob,
  'analysis' : MusicAnalysis,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoRecord)], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [VideoRecord], ['query']),
  'uploadAudio' : IDL.Func([IDL.Text, ExternalBlob], [UploadResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MusicAnalysis = IDL.Record({
    'tempo' : IDL.Nat,
    'emotion' : IDL.Text,
    'genre' : IDL.Text,
    'rhythm' : IDL.Text,
  });
  const VideoRecord = IDL.Record({
    'id' : IDL.Text,
    'user' : IDL.Principal,
    'audioFile' : ExternalBlob,
    'videoFile' : IDL.Opt(ExternalBlob),
    'analysis' : MusicAnalysis,
  });
  const UploadResult = IDL.Record({
    'id' : IDL.Text,
    'audioFile' : ExternalBlob,
    'analysis' : MusicAnalysis,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoRecord)], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [VideoRecord], ['query']),
    'uploadAudio' : IDL.Func([IDL.Text, ExternalBlob], [UploadResult], []),
  });
};

export const init = ({ IDL }) => { return []; };